name: frame_vision
description: "Foundation for Frame Vision apps. Takes repeated snapshots and feeds into a machine vision pipeline."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.7.1
  google_mlkit_image_labeling: ^0.12.0
  image: ^4.2.0
  image_mlkit_converter: ^0.0.1
  logging: ^1.2.0
  simple_frame_app:
    git: https://github.com/CitizenOneX/simple_frame_app.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/battery.min.lua
    - assets/camera.min.lua
    - assets/data.min.lua
    - assets/frame_app.min.lua
    - assets/sprites/20_hotdog.png
    - assets/sprites/21_text_hotdog.png
    - assets/sprites/22_nothotdog.png
    - assets/sprites/23_text_nothotdog.png
