name: frame_vision_hotdog
description: "Hot Dog / Not Hot Dog detector app for Frame"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.7.1
  google_mlkit_image_labeling: ^0.12.0
  image: ^4.2.0
  image_mlkit_converter: ^0.0.1
  logging: ^1.2.0
  simple_frame_app:
    path: ../simple_frame_app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/simple_frame_app/lua/battery.min.lua
    - packages/simple_frame_app/lua/camera.min.lua
    - packages/simple_frame_app/lua/code.min.lua
    - packages/simple_frame_app/lua/data.min.lua
    - packages/simple_frame_app/lua/sprite.min.lua
    - assets/frame_app.min.lua
    - assets/sprites/20_hotdog128.png
    - assets/sprites/21_text_hotdog.png
    - assets/sprites/22_nothotdog128.png
    - assets/sprites/23_text_nothotdog.png
